### ISSUE TITLE
Unable to find 'change-case' module after mdx install.  

### ISSUE THREAD

**Issue by evankilleen** [FrontendMasters/gatsby-intro#22]
![Screen Shot 2019-07-18 at 4 48 53 PM](https://user-images.githubusercontent.com/18077853/61497201-fa7bce00-a97b-11e9-9f22-c1bca67c6b85.png)

In the Blog Posts section of the Gatsby course during the first part, Rendering Components in MDX, after installing the mdx plugin, this error popped up and prevented me from restarting the development server.  

Also, cleaned the cache and deleted/re-installed node_modules, but the error remained.

**Comment by MichaelAdamBerry** [comment]
I ran into the same issue. I dug around the Gatsby docs and saw that they use gatsby-plugin-mdx instead of gatsby-mdx. Install gatsby-plugin-mdx and change the plugin in gatsby-config to resolve to 'gatsby-plugin-mdx'. This seems to have solved the issue for me.

**Comment by evankilleen** [comment]
@MichaelAdamBerry Thanks, that did the trick!
