### ISSUE TITLE
mdx graphql query structure doesn't have "code"

### ISSUE THREAD

**Issue by davinakano** [FrontendMasters/gatsby-intro#26]
Hi 👋 

First of all, fantastic course! So far, I have been enjoying a lot. Kudos!

I have been following the course but got a little bit stuck in the following video:
https://frontendmasters.com/courses/gatsby/getting-post-data-by-slug/

Turns out that instead of
```
query($slug: String!) {
    mdx(frontmatter: { slug: { eq: $slug } }) {
      frontmatter {
        title
        author
      }
      code {
        body
      }
    }
  }
```

I had to use:
```
query($slug: String!) {
    mdx(frontmatter: { slug: { eq: $slug } }) {
      frontmatter {
        title
        author
      }
      body
    }
  }
```

**Seems that there's no `code` under `mdx()`.**

If someone run into the same issue, please give it a try!

Cheers!

**Comment by luis-echegaray** [comment]
saw the same thing and came to post about it! good looking out @davinakano !

**Comment by 1Marc** [comment]
Added to the [course errata](https://github.com/FrontendMasters/gatsby-intro#gatsby-plugin-mdx-no-longer-requires-body-to-be-nested-in-code-in-the-query) as well as in a pop up annotation to the course... thanks @davinakano @denvercoder @luis-echegaray !

<img width="841" alt="Screen Shot 2019-12-03 at 1 44 43 PM" src="https://user-images.githubusercontent.com/19269/70084022-29b17580-15d3-11ea-9092-697eefc56535.png">
