### ISSUE TITLE
Double images fix

### ISSUE THREAD

**Issue by tonilaukka** [FrontendMasters/gatsby-intro#28]
There is a known [issue](https://github.com/gatsbyjs/gatsby/issues/15486) with `gatsby-plugin-mdx` and `gatsby-remark-issue` which results in double images with the config described in the course.  This can be fixed by adding `gatsby-remark-images` as plugin of  `gatsby-plugin-mxd`.

```
    {
      resolve: 'gatsby-plugin-mdx',
      options: {
        defaultLayouts: {
          default: require.resolve('./src/components/layout.js'),
        },
        gatsbyRemarkPlugins: ['gatsby-remark-images'],
        plugins: ['gatsby-remark-images'],
      },
    },
```

**Comment by 1Marc** [comment]
This was added as an annotation, but is now also added as a code snippet to the [course errata](https://github.com/FrontendMasters/gatsby-intro/blob/master/README.md#course-errata).
