### ISSUE TITLE
images/xxx.jpg doesn't show, even not try sharp it yet.

### ISSUE THREAD

**Issue by luml** [FrontendMasters/gatsby-intro#30]
Here's my hero.js a part code:
const ImageBackground = styled('div')`
  background-image: url('/images/zhang-kaiyv-beijing.jpg');
  background-position: top 20% center;
  background-size: cover;
  height: 50vh;

  + * {
    margin-top: 0;
  }
`;

...

const Hero = () => {
  return (
    // We don't do any sharp process for hero image yet
    <ImageBackground>
      <TextBox>
        <h1>Frontend Masters + Gatsby &hearts;</h1>
        <p>
          Hello Bejing! <Link to="/about/">Learn about me &rarr;</Link>
        </p>
      </TextBox>
    </ImageBackground>
  )
};

Then, I get it in index.js like this:
  return (
    <>
      <Hero />
      <Layout>
        <h2>Read my blog</h2>
        {posts.map(post => (
          <PostPreview key={post.slug} post={post} />
        ))}
      </Layout>
    </>
  );

But, somehow, homePage can't get this image.

**Comment by 1Marc** [comment]
Please refer to the course branches for example, working code.
